# Manual Labeling Interface: NLP

Sam Showalter

2021-06-01

Welcome to hell. This is where you will manually tag 4 articles for humanitarian categories so that we can log performance. Get comfortable, this should be fun

## Recommended Approach

- I will send out a picture that maps the label codes to the word labels for your reference. Keep that puppy up on your screen somewhere
- I will also generate a "qual_samples_{your_name}.pkl" file for you. This will provide you the tokens for your article as well as the predicted labels. The predicted labels will likely not be completely right, which is where you come in
- Using the legend, copy over the output into a text file. The script below will print the lines, one at a time, with the predictions. Use this as your starting point, and work your way through them.
- Once you are done, copy that list of lists back into Jupyter, and save it in a dictionary where the key is the article name and the values are the list of lists that represent the gold labels

In [2]:
import pickle as pkl
import numpy as np

In [3]:
# Replace this path with your file!
with open('../artifacts/qual_samples_showalte.pkl','rb') as file:
    d = pkl.load(file)

In [4]:
print(d.keys())

dict_keys(['dorian_nyt', 'dorian_wiki', 'dorian_usatoday', 'canada_wildfire_nyt', 'le'])


In [5]:
for i in range(10):
    print(i, d['le'].inverse_transform([i]))

0 ['caution_and_advice']
1 ['displaced_people_and_evacuations']
2 ['infrastructure_and_utility_damage']
3 ['injured_or_dead_people']
4 ['missing_or_found_people']
5 ['not_humanitarian']
6 ['other_relevant_information']
7 ['requests_or_urgent_needs']
8 ['rescue_volunteering_or_donation_effort']
9 ['sympathy_and_support']


In [5]:
crisis = 'canada_wildfire_nyt'

In [34]:
for j in range(len(d[crisis]['tokens'])):
#     print(j)
    print([(i,d,e) for i,d,e in zip(range(len(d[crisis]['tokens'][j])), d[crisis]['tokens'][j],d[crisis]['preds'][j])])
    print()
    print(d[crisis]['tokens'][j]) 
    print()
    index = np.array(list(range(len(d[crisis]['preds'][j]))))
    preds = np.array(d[crisis]['preds'][j])
    print(np.vstack((index,preds)))
    print()
    print(list(preds), ",")
    print("-----"*15)

[(0, 'Fort', 5), (1, 'McMurray', 5), (2, 'Blaze', 5), (3, 'Fast', 6), (4, 'and', 6), (5, 'Unpredictable', 6), (6, 'Keeps', 6), (7, 'Firefighters', 6), (8, 'at', 6), (9, 'Distance', 6)]

['Fort', 'McMurray', 'Blaze', 'Fast', 'and', 'Unpredictable', 'Keeps', 'Firefighters', 'at', 'Distance']

[[0 1 2 3 4 5 6 7 8 9]
 [5 5 5 6 6 6 6 6 6 6]]

[5, 5, 5, 6, 6, 6, 6, 6, 6, 6] ,
---------------------------------------------------------------------------
[(0, 'By', 5), (1, 'Ian', 5), (2, 'Austen', 5)]

['By', 'Ian', 'Austen']

[[0 1 2]
 [5 5 5]]

[5, 5, 5] ,
---------------------------------------------------------------------------
[(0, 'May', 6), (1, '2016', 6)]

['May', '2016']

[[0 1]
 [6 6]]

[6, 6] ,
---------------------------------------------------------------------------
[(0, 'OTTAWA', 2), (1, 'Walls', 2), (2, 'of', 2), (3, 'flame', 2), (4, 'driven', 2), (5, 'by', 2), (6, 'strong', 2), (7, 'shifting', 2), (8, 'winds', 2), (9, 'raged', 2), (10, 'out', 2), (11, 'of', 2), (12, 'control', 

In [33]:
golds = [
   #Put manual gold labels here 
    
]

In [32]:
print(crisis)
for i in range(len(golds)):
#     print(d[crisis]['preds'][i])
    print(len(golds[i]), len(d[crisis]['preds'][i]))
#     print(golds[i])
    assert len(golds[i]) == len(d[crisis]['preds'][i]),"Error: sample {}".format(i)

canada_wildfire_nyt
10 10
3 3
2 2
43 43
33 33
30 30
43 43
73 73
63 63
74 74
62 62
34 34
53 53
70 70
59 59
58 58
24 24
29 29
75 75
54 54
43 43
75 75
92 92
38 38
58 58
66 66


In [31]:
# Check your performance (make sure nothing is misaligned or weird)
assert len(golds) == len(d[crisis]['preds'])
c = 0
t = 0
for i in range(len(golds)):
    t += len(golds[i])
    preds = np.array(d[crisis]['preds'][i])
    l = np.array(golds[i])
    c += (preds == l).sum()

print(c/t)

0.8306962025316456


In [ ]:
# Use this to store your gold labels

### Sam's Gold Labels - Do NOT edit this

In [6]:
golds_nyt_can_fire = [
[6,6,6, 6, 6, 6, 6, 6, 6, 6] ,
[5, 5, 5] ,
[6, 6] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,1,1,1,1,1,1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] ,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1,1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6,6,6,6,6,6,6,6] ,
[5]*27 + [ 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] + [5]*24,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,5,5,5,5,5,5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,1,1,1,1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6,6,6,6,6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,6,6,6,6,6,6,6, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9] ,
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9] + [5]*14 ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] + [6]*10 ,
[5]*25 + [1, 1, 1, 1, 1, 1,1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0,0,0,0,0,0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] + [8]*16 ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[1]*18 + [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] + [8]*13 

]

In [7]:
golds_nyt_dorian = [
[6, 6, 6, 6, 6, 6, 6] ,
[5,5,5] ,
[5, 5, 5] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[5]*18 + [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,0] ,
[6]*20 + [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[6]*27 + [ 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6]*25,
[5]*12,
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9] ,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7,7,7,7,7,7,7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6, 6, 6, 6, 6, 6, 6, 7,7,7,7,7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7,7] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8] ,
[6, 6, 6, 6, 6] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,1,1,1] ,
[5]*24,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[0, 0, 0, 0, 0, 0, 0, 0, 5,5,5,5,5,5,5,5,5,5,5,5,5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[5,5,5,5,5,5,5,5,5,5,5,5, 2,2,2,2,2,2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] ,
[5]*21,
[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9] ,
[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8] ,
[6]*13,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[5]*40,
[5]*38,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[5]*29,
[6]*28,
[5]*47,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[6]*30,
[6]*40,
[5]*28,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
]

In [8]:
golds_wiki_dorian = [
[6]*33,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[5]*23,
[6]*36,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,1,1,1,1,1,1,1] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6,6,6,6,6,6,6,6,6,6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6]*16,
[6]*23,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,3,3] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1] ,
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,3,3, 3, 3, 3, 3, 3, 3, 3,3,3] ,
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3] ,
[2, 2, 2, 2, 2, 2, 2, 4,4,4,4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
]

In [9]:
golds_dorian_usatoday = [
[5]*11,
[5,5],
[5,5],
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3] ,
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,6,6,6,6,6,6,6,6,6,6,6, 3, 3, 3, 3, 3, 3, 3] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[6]*27,
[5]*47,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6] ,
[5]*29,
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2] ,
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5,5,5,5,5,5,5,5] ,
[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3] ,
[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9] ,
[3]*13,
[6]*18 + [5]*22,
[5]*47,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,
[3, 3, 3, 3, 3, 3, 3, 3, 3] + [5]*28 ,
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5] ,

]

In [ ]:
['dorian_nyt', 'dorian_wiki', 'dorian_usatoday', 'canada_wildfire_nyt', 'le']

In [11]:
sams_golds = {'dorian_nyt':[d['dorian_wiki']['preds'],golds_wiki_dorian],
             'dorian_usatoday':[d['dorian_usatoday']['preds'],golds_dorian_usatoday],
             'dorian_nyt':[d['dorian_nyt']['preds'],golds_nyt_dorian],
             'can_wfire_nyt':[d['canada_wildfire_nyt']['preds'],golds_nyt_can_fire]}

In [12]:
with open('../artifacts/sams_articles_preds_golds.pkl','wb') as file:
    pkl.dump(sams_golds,file)