# Manual Labeling Interface: NLP

Sam Showalter

2021-06-01

Welcome to hell. This is where you will manually tag 4 articles for humanitarian categories so that we can log performance. Get comfortable, this should be fun

## Recommended Approach

- I will send out a picture that maps the label codes to the word labels for your reference. Keep that puppy up on your screen somewhere
- I will also generate a "qual_samples_{your_name}.pkl" file for you. This will provide you the tokens for your article as well as the predicted labels. The predicted labels will likely not be completely right, which is where you come in
- Using the legend, copy over the output into a text file. The script below will print the lines, one at a time, with the predictions. Use this as your starting point, and work your way through them.
- Once you are done, copy that list of lists back into Jupyter, and save it in a dictionary where the key is the article name and the values are the list of lists that represent the gold labels

In [2]:
import pickle as pkl
import numpy as np

In [3]:
with open('../artifacts/qual_samples_showalte.pkl','rb') as file:
    d = pkl.load(file)

In [4]:
print(d.keys())

dict_keys(['dorian_nyt', 'dorian_wiki', 'dorian_usatoday', 'canada_wildfire_nyt', 'le'])


In [5]:
for i in range(10):
    print(i, d['le'].inverse_transform([i]))

0 ['caution_and_advice']
1 ['displaced_people_and_evacuations']
2 ['infrastructure_and_utility_damage']
3 ['injured_or_dead_people']
4 ['missing_or_found_people']
5 ['not_humanitarian']
6 ['other_relevant_information']
7 ['requests_or_urgent_needs']
8 ['rescue_volunteering_or_donation_effort']
9 ['sympathy_and_support']


In [12]:
crisis = 'canada_wildfire_nyt'

In [13]:
for j in range(len(d[crisis]['tokens'])):
#     print(j)
    print(d[crisis]['tokens'][j]) 
    print()
    print([(i,d,e) for i,d,e in zip(range(len(d[crisis]['tokens'])), d[crisis]['tokens'][j],d[crisis]['preds'][j])])
    print()
    index = np.array(list(range(len(d[crisis]['preds'][j]))))
    preds = np.array(d[crisis]['preds'][j])
    print(np.vstack((index,preds)))
    print("-----"*15)

['Fort', 'McMurray', 'Blaze', 'Fast', 'and', 'Unpredictable', 'Keeps', 'Firefighters', 'at', 'Distance']

[(0, 'Fort', 5), (1, 'McMurray', 5), (2, 'Blaze', 5), (3, 'Fast', 6), (4, 'and', 6), (5, 'Unpredictable', 6), (6, 'Keeps', 6), (7, 'Firefighters', 6), (8, 'at', 6), (9, 'Distance', 6)]

[[0 1 2 3 4 5 6 7 8 9]
 [5 5 5 6 6 6 6 6 6 6]]
---------------------------------------------------------------------------
['By', 'Ian', 'Austen']

[(0, 'By', 5), (1, 'Ian', 5), (2, 'Austen', 5)]

[[0 1 2]
 [5 5 5]]
---------------------------------------------------------------------------
['May', '2016']

[(0, 'May', 6), (1, '2016', 6)]

[[0 1]
 [6 6]]
---------------------------------------------------------------------------
['OTTAWA', 'Walls', 'of', 'flame', 'driven', 'by', 'strong', 'shifting', 'winds', 'raged', 'out', 'of', 'control', 'on', 'Wednesday', 'in', 'and', 'around', 'the', 'evacuated', 'city', 'of', 'Fort', 'McMurray', 'Alberta', 'where', 'firefighters', 'were', 'helpless', 'to', 's